### DATE: Friday, August 28th
#### Lecture Narrative

In [1]:
import pandas

In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3])


In [4]:
a.shape

(4,)

In [5]:
a = np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

In [6]:
[[1,2,3],[1,2,3]]

[[1, 2, 3], [1, 2, 3]]

In [7]:
bb = [[1,2,3],[1,2,3]]

In [8]:
whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    4: 4 elems, type `int64`, 32 bytes
bb         list       n=2
np         module     <module 'numpy' from '/us<...>ages/numpy/__init__.pyc'>
pandas     module     <module 'pandas' from '/u<...>ges/pandas/__init__.pyc'>


In [16]:
dc = np.array([[[1,2], [2,3]], [[3,3], [4,3]]])

In [17]:
dc

array([[[1, 2],
        [2, 3]],

       [[3, 3],
        [4, 3]]])

In [11]:
c.shape

(2, 2, 1)

In [12]:
whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    4: 4 elems, type `int64`, 32 bytes
bb         list       n=2
c          ndarray    2x2x1: 4 elems, type `int64`, 32 bytes
np         module     <module 'numpy' from '/us<...>ages/numpy/__init__.pyc'>
pandas     module     <module 'pandas' from '/u<...>ges/pandas/__init__.pyc'>


In [13]:
c.ndim()

TypeError: 'int' object is not callable

In [14]:
c.ndim

3

In [15]:
c.ndim

3

In [18]:
d

NameError: name 'd' is not defined

### to start with x number of arrays - start with 4 brackets.  Brackets indicate the number of dimensions

### to slice, use arange


In [19]:
c = np.arange(1, 19, 3)

In [20]:
c

array([ 1,  4,  7, 10, 13, 16])

In [21]:
c = np.linspace(0, 1, 6) # start end num-points

In [22]:
c

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [26]:
c = np.eye(3)

### Random number generation

In [27]:
np.random.rand?

In [28]:
np.random.rand(1)

array([ 0.1220511])

In [29]:
np.random.rand(5)

array([ 0.83200993,  0.07029638,  0.12512175,  0.13796564,  0.87202916])

In [32]:
np.random.rand(4,5).shape

(4, 5)

In [36]:
np.random.seed(1234) # - set the seed

In [34]:
np.random.rand(5)

array([ 0.19151945,  0.62210877,  0.43772774,  0.78535858,  0.77997581])

In [38]:
np.random.rand(5)

array([ 0.27259261,  0.27646426,  0.80187218,  0.95813935,  0.87593263])

In [39]:
a = np.arange(10)

In [41]:
a[1:4:2]  #- subset

array([1, 3])

In [42]:
a[::2]

array([0, 2, 4, 6, 8])

In [43]:
a[::-2]

array([9, 7, 5, 3, 1])

In [48]:
a[::2]

array([0, 2, 4, 6, 8])